spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa  
  jpa:
    properties:    
      javax: 
        persistence:
          validation:
            mode: none  